### ISSUE TITLE
 Water Bill Payment via Paytm

### ISSUE THREAD

**Issue by cmvyas** [cmvyas/App_Guide#3]
Guide for  water bill payment, include each and every step to make it more understandable.

**Comment by nitin-pandita** [comment]
I want to do this . If you can just assign me I will start working on it

**Comment by gitmank** [comment]
I would like to do this please assign it to me

**Comment by cmvyas** [comment]
@gitmank hey if you want , you can add for "transferring money to bank account using UPI "

**Comment by nitin-pandita** [comment]
> @gitmank hey if you want , you can add for "transferring money to bank account using UPI "

Yeh sure No problem!
