### ISSUE TITLE
Book Bus Ticket using RedBus

### ISSUE THREAD

**Issue by cmvyas** [cmvyas/App_Guide#8]
Add a guide to book bus ticket, make sure to cover every small step, to make it easier to understand

**Comment by gitmank** [comment]
I would like to do this please assign it to me

**Comment by nitin-pandita** [comment]
I can do this . If you like i can get started with this.

**Comment by iaryangoyal** [comment]
@cmvyas I would like to do this

**Comment by cmvyas** [comment]
@nitin-pandita @iaryangoyal guys other issues are open, go for them

**Comment by cmvyas** [comment]
@Rashmisingh-18 yes it is, u can see the github page for demo purpose it is simple html css only , go for it
